import json
import sqlite3

mapping = {
    # East
    "Assam University, Silchar": ("Assam", "East"),
    "Birla Institute of Technology, Deoghar Off-Campus": ("Jharkhand", "East"),
    "Birla Institute of Technology, Mesra,  Ranchi": ("Jharkhand", "East"),
    "Birla Institute of Technology, Patna Off-Campus": ("Bihar", "East"),
    "Central institute of Technology Kokrajar, Assam": ("Assam", "East"),
    "CU Jharkhand": ("Jharkhand", "East"),
    "Ghani Khan Choudhary Institute of Engineering and Technology, Malda, West Bengal": ("West Bengal", "East"),
    "Indian Institute of Engineering Science and Technology, Shibpur": ("West Bengal", "East"),
    "Indian Institute  of Technology (ISM) Dhanbad": ("Jharkhand", "East"),
    "Indian Institute  of Technology Bhubaneswar": ("Odisha", "East"),
    "Indian Institute  of Technology Guwahati": ("Assam", "East"),
    "Indian Institute  of Technology Kharagpur": ("West Bengal", "East"),
    "Indian Institute  of Technology Patna": ("Bihar", "East"),
    "Indian Institute of Information Technology (IIIT) Ranchi": ("Jharkhand", "East"),
    "Indian Institute of Information Technology(IIIT) Kalyani, West Bengal": ("West Bengal", "East"),
    "Indian Institute of Information Technology Bhagalpur": ("Bihar", "East"),
    "Indian Institute of Information Technology Guwahati": ("Assam", "East"),
    "INDIAN INSTITUTE OF INFORMATION TECHNOLOGY SENAPATI MANIPUR": ("Manipur", "East"),
    "Indian Institute of Information Technology, Agartala": ("Tripura", "East"),
    "Institute of Chemical Technology, Mumbai: Indian Oil Odisha Campus, Bhubaneswar": ("Odisha", "East"),
    "International Institute of Information Technology, Bhubaneswar": ("Odisha", "East"),
    "International Institute of Information Technology, Naya Raipur": ("Chhattisgarh", "East"),
    "Mizoram University, Aizawl": ("Mizoram", "East"),
    "National Institute of Advanced Manufacturing Technology, Ranchi": ("Jharkhand", "East"),
    "National Institute of Technology  Agartala": ("Tripura", "East"),
    "National Institute of Technology Arunachal Pradesh": ("Arunachal Pradesh", "East"),
    "National Institute of Technology Durgapur": ("West Bengal", "East"),
    "National Institute of Technology Meghalaya": ("Meghalaya", "East"),
    "National Institute of Technology Nagaland": ("Nagaland", "East"),
    "National Institute of Technology Patna": ("Bihar", "East"),
    "National Institute of Technology Raipur": ("Chhattisgarh", "East"),
    "National Institute of Technology Sikkim": ("Sikkim", "East"),
    "National Institute of Technology, Jamshedpur": ("Jharkhand", "East"),
    "National Institute of Technology, Manipur": ("Manipur", "East"),
    "National Institute of Technology, Mizoram": ("Mizoram", "East"),
    "National Institute of Technology, Rourkela": ("Odisha", "East"),
    "National Institute of Technology, Silchar": ("Assam", "East"),
    "North Eastern Regional Institute of Science and Technology, Nirjuli-791109 (Itanagar),Arunachal Pradesh": ("Arunachal Pradesh", "East"),
    "North-Eastern Hill University, Shillong": ("Meghalaya", "East"),
    "School of Engineering, Tezpur University, Napaam, Tezpur": ("Assam", "East"),
    "School of Studies of Engineering and Technology, Guru Ghasidas Vishwavidyalaya, Bilaspur": ("Chhattisgarh", "East"),
    "Chhattisgarh Swami Vivekanada Technical University, Bhilai (CSVTU Bhilai)": ("Chhattisgarh", "East"),
    "Indian Institute of Technology Bhilai": ("Chhattisgarh", "East"),

    # North
    "Atal Bihari Vajpayee Indian Institute of Information Technology & Management Gwalior": ("Madhya Pradesh", "North"),
    "Central University of Haryana": ("Haryana", "North"),
    "Central University of Jammu": ("Jammu & Kashmir", "North"),
    "Central University of Rajasthan, Rajasthan": ("Rajasthan", "North"),
    "Dr. B R Ambedkar National Institute of Technology, Jalandhar": ("Punjab", "North"),
    "Gurukula Kangri Vishwavidyalaya, Haridwar": ("Uttarakhand", "North"),
    "Indian Institute  of Technology (BHU) Varanasi": ("Uttar Pradesh", "North"),
    "Indian Institute  of Technology Delhi": ("Delhi", "North"),
    "Indian Institute  of Technology Indore": ("Madhya Pradesh", "North"),
    "Indian Institute  of Technology Jodhpur": ("Rajasthan", "North"),
    "Indian Institute  of Technology Kanpur": ("Uttar Pradesh", "North"),
    "Indian Institute  of Technology Mandi": ("Himachal Pradesh", "North"),
    "Indian Institute  of Technology Roorkee": ("Uttarakhand", "North"),
    "Indian Institute  of Technology Ropar": ("Punjab", "North"),
    "Indian Institute of Technology Jammu": ("Jammu & Kashmir", "North"),
    "Indian Institute of Information Technology (IIIT)Kota, Rajasthan": ("Rajasthan", "North"),
    "Indian Institute of Information Technology(IIIT) Kilohrad, Sonepat, Haryana": ("Haryana", "North"),
    "Indian Institute of Information Technology(IIIT) Una, Himachal Pradesh": ("Himachal Pradesh", "North"),
    "Indian Institute of Information Technology, Allahabad": ("Uttar Pradesh", "North"),
    "Pt. Dwarka Prasad Mishra Indian Institute of Information Technology, Design & Manufacture Jabalpur": ("Madhya Pradesh", "North"),
    "Indian Institute of Information Technology Lucknow": ("Uttar Pradesh", "North"),
    "Indian Institute of Information Technology Bhopal": ("Madhya Pradesh", "North"),
    "Indian Institute of Carpet Technology,  Bhadohi": ("Uttar Pradesh", "North"),
    "Indian Institute of Handloom Technology(IIHT), Varanasi": ("Uttar Pradesh", "North"),
    "Institute of Engineering and Technology, Dr. H. S. Gour University. Sagar (A Central University)": ("Madhya Pradesh", "North"),
    "J.K. Institute of Applied Physics & Technology, Department of Electronics & Communication, University of Allahabad- Allahabad": ("Uttar Pradesh", "North"),
    "Jawaharlal Nehru University, Delhi": ("Delhi", "North"),
    "Malaviya National Institute of Technology Jaipur": ("Rajasthan", "North"),
    "Maulana Azad National Institute of Technology Bhopal": ("Madhya Pradesh", "North"),
    "Motilal Nehru National Institute of Technology Allahabad": ("Uttar Pradesh", "North"),
    "National Institute of Food Technology Entrepreneurship and Management, Kundli": ("Haryana", "North"),
    "National Institute of Technology Delhi": ("Delhi", "North"),
    "National Institute of Technology Hamirpur": ("Himachal Pradesh", "North"),
    "National Institute of Technology, Kurukshetra": ("Haryana", "North"),
    "National Institute of Technology, Srinagar": ("Jammu & Kashmir", "North"),
    "National Institute of Technology, Uttarakhand": ("Uttarakhand", "North"),
    "Punjab Engineering College, Chandigarh": ("Chandigarh", "North"),
    "Sant Longowal Institute of Engineering and Technology": ("Punjab", "North"),
    "School of Planning & Architecture, Bhopal": ("Madhya Pradesh", "North"),
    "School of Planning & Architecture, New Delhi": ("Delhi", "North"),
    "Shri Mata Vaishno Devi University, Katra, Jammu & Kashmir": ("Jammu & Kashmir", "North"),

    # South
    "Indian Institute  of Technology Hyderabad": ("Telangana", "South"),
    "Indian Institute  of Technology Madras": ("Tamil Nadu", "South"),
    "Indian Institute  of Technology Palakkad": ("Kerala", "South"),
    "Indian Institute  of Technology Tirupati": ("Andhra Pradesh", "South"),
    "Indian Institute of Technology Dharwad": ("Karnataka", "South"),
    "Indian Institute of Information Technology (IIIT), Sri City, Chittoor": ("Andhra Pradesh", "South"),
    "Indian Institute of Information Technology, Design & Manufacturing, Kancheepuram": ("Tamil Nadu", "South"),
    "Indian Institute of Information Technology Tiruchirappalli": ("Tamil Nadu", "South"),
    "Indian Institute of Information Technology(IIIT) Dharwad": ("Karnataka", "South"),
    "Indian Institute of Information Technology Design & Manufacturing Kurnool, Andhra Pradesh": ("Andhra Pradesh", "South"),
    "Indian Institute of Information Technology(IIIT) Kottayam": ("Kerala", "South"),
    "Indian institute of information technology, Raichur, Karnataka": ("Karnataka", "South"),
    "Indian Institute of Handloom Technology, Salem": ("Tamil Nadu", "South"),
    "National Institute of Food Technology Entrepreneurship and Management, Thanjavur": ("Tamil Nadu", "South"),
    "National Institute of Technology Calicut": ("Kerala", "South"),
    "National Institute of Technology Karnataka, Surathkal": ("Karnataka", "South"),
    "National Institute of Technology Puducherry": ("Puducherry", "South"),
    "National Institute of Technology, Tiruchirappalli": ("Tamil Nadu", "South"),
    "National Institute of Technology, Warangal": ("Telangana", "South"),
    "National Institute of Technology, Andhra Pradesh": ("Andhra Pradesh", "South"),
    "Puducherry Technological University, Puducherry": ("Puducherry", "South"),
    "School of Planning & Architecture: Vijayawada": ("Andhra Pradesh", "South"),
    "University of Hyderabad": ("Telangana", "South"),

    # West
    "Gati Shakti Vishwavidyalaya, Vadodara": ("Gujarat", "West"),
    "Indian Institute  of Technology Bombay": ("Maharashtra", "West"),
    "Indian Institute  of Technology Gandhinagar": ("Gujarat", "West"),
    "Indian Institute of Technology Goa": ("Goa", "West"),
    "Indian Institute of Information Technology(IIIT), Vadodara, Gujrat": ("Gujarat", "West"),
    "Indian Institute of Information Technology (IIIT) Nagpur": ("Maharashtra", "West"),
    "Indian Institute of Information Technology (IIIT) Pune": ("Maharashtra", "West"),
    "Indian Institute of Information Technology Surat": ("Gujarat", "West"),
    "Indian Institute of Information Technology, Vadodara International Campus Diu (IIITVICD)": ("Gujarat", "West"),
    "Institute of Infrastructure, Technology, Research and Management-Ahmedabad": ("Gujarat", "West"),
    "National Institute of Electronics and Information Technology, Aurangabad (Maharashtra)": ("Maharashtra", "West"),
    "National Institute of Technology Goa": ("Goa", "West"),
    "Sardar Vallabhbhai National Institute of Technology, Surat": ("Gujarat", "West"),
    "Visvesvaraya National Institute of Technology, Nagpur": ("Maharashtra", "West"),
}

conn = sqlite3.connect('rank_wise.db')
curs = conn.cursor()
curs.execute('SELECT DISTINCT institute FROM colleges')
rows = curs.fetchall()

missing = []

for r in rows:
    inst = r[0]
    if inst not in mapping:
        missing.append(inst)

print(f"Missing mapping for: {missing}")
